/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controller.Main;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import models.Exercicio;

/**
 *
 * @author tiovi
 */
public class TelaExercicioAdicionar extends javax.swing.JPanel {
    Exercicio exercicio;
    ResourceBundle traducoes;
    /**
     * Creates new form TelaExercicioAdicionar
     */
    public TelaExercicioAdicionar() {
        initComponents();
        exercicio = new Exercicio();
        this.traducoes = Main.controllerManager.getTraducoes();
        traduzir();
    }
    
    public void traduzir(){
        lb_cliente.setText(this.traducoes.getString("lb_cliente"));
        lb_instrutor.setText(this.traducoes.getString("lb_instrutor"));
        lb_plano.setText(this.traducoes.getString("lb_plano"));
        lb_exercicio.setText(this.traducoes.getString("lb_exercicio"));
        lb_modalidade.setText(this.traducoes.getString("lb_modalidade"));
        lb_treino.setText(this.traducoes.getString("lb_treino"));
        lb_titAddExec.setText(this.traducoes.getString("lb_titAddExec"));
        lb_Musculo.setText(this.traducoes.getString("lb_Musculo"));
        lb_txtAddExercicio.setText(this.traducoes.getString("lb_txtAddEx"));
        lb_Nome.setText(this.traducoes.getString("lb_NomeEx"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Musculo = new javax.swing.JLabel();
        lb_titAddExec = new javax.swing.JLabel();
        lb_logo = new javax.swing.JLabel();
        lb_cliente = new javax.swing.JLabel();
        lb_treino = new javax.swing.JLabel();
        lb_modalidade = new javax.swing.JLabel();
        lb_exercicio = new javax.swing.JLabel();
        lb_instrutor = new javax.swing.JLabel();
        lb_plano = new javax.swing.JLabel();
        lb_sideBar = new javax.swing.JLabel();
        lb_txtAddExercicio = new javax.swing.JLabel();
        lb_botaoAddExercicio = new javax.swing.JLabel();
        lb_Nome = new javax.swing.JLabel();
        cb_Musculo = new javax.swing.JComboBox<>();
        tf_Nome = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lb_Musculo.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_Musculo.setText("Músculo:");
        add(lb_Musculo);
        lb_Musculo.setBounds(440, 260, 180, 30);

        lb_titAddExec.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 18)); // NOI18N
        lb_titAddExec.setText("Adicionar Exercicio");
        add(lb_titAddExec);
        lb_titAddExec.setBounds(440, 240, 270, 20);

        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/preto.png"))); // NOI18N
        add(lb_logo);
        lb_logo.setBounds(30, 40, 190, 120);

        lb_cliente.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_cliente.setText("Cliente");
        lb_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_clienteMouseClicked(evt);
            }
        });
        add(lb_cliente);
        lb_cliente.setBounds(0, 190, 250, 40);

        lb_treino.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_treino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_treino.setText("Treino");
        lb_treino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_treino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_treinoMouseClicked(evt);
            }
        });
        add(lb_treino);
        lb_treino.setBounds(0, 490, 250, 40);

        lb_modalidade.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_modalidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_modalidade.setText("Modalidade");
        lb_modalidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_modalidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_modalidadeMouseClicked(evt);
            }
        });
        add(lb_modalidade);
        lb_modalidade.setBounds(0, 430, 250, 40);

        lb_exercicio.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        lb_exercicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_exercicio.setText("Exercício");
        lb_exercicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_exercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_exercicioMouseClicked(evt);
            }
        });
        add(lb_exercicio);
        lb_exercicio.setBounds(0, 370, 250, 40);

        lb_instrutor.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_instrutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_instrutor.setText("Instrutor");
        lb_instrutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_instrutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_instrutorMouseClicked(evt);
            }
        });
        add(lb_instrutor);
        lb_instrutor.setBounds(0, 250, 250, 40);

        lb_plano.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        lb_plano.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_plano.setText("Plano");
        lb_plano.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_plano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_planoMouseClicked(evt);
            }
        });
        add(lb_plano);
        lb_plano.setBounds(0, 310, 250, 40);

        lb_sideBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sidebar_verde.png"))); // NOI18N
        add(lb_sideBar);
        lb_sideBar.setBounds(0, 0, 254, 720);

        lb_txtAddExercicio.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 16)); // NOI18N
        lb_txtAddExercicio.setForeground(new java.awt.Color(255, 255, 255));
        lb_txtAddExercicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_txtAddExercicio.setText("ADICIONAR EXERCICIO");
        lb_txtAddExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_txtAddExercicioMouseClicked(evt);
            }
        });
        add(lb_txtAddExercicio);
        lb_txtAddExercicio.setBounds(850, 400, 260, 30);

        lb_botaoAddExercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bt-azul.png"))); // NOI18N
        lb_botaoAddExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_botaoAddExercicioMouseClicked(evt);
            }
        });
        add(lb_botaoAddExercicio);
        lb_botaoAddExercicio.setBounds(850, 380, 260, 70);

        lb_Nome.setFont(new java.awt.Font("Montserrat", 0, 16)); // NOI18N
        lb_Nome.setText("Nome exericio:");
        add(lb_Nome);
        lb_Nome.setBounds(440, 380, 250, 30);

        cb_Musculo.setBackground(new java.awt.Color(153, 255, 51));
        cb_Musculo.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        cb_Musculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peito", "Costas", "Braço", "Perna", "Ombro" }));
        cb_Musculo.setToolTipText("");
        add(cb_Musculo);
        cb_Musculo.setBounds(440, 290, 320, 40);

        tf_Nome.setBackground(new java.awt.Color(238, 238, 238));
        tf_Nome.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tf_Nome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NomeActionPerformed(evt);
            }
        });
        add(tf_Nome);
        tf_Nome.setBounds(440, 410, 320, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NomeActionPerformed

    private void lb_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_clienteMouseClicked
        Main.controllerManager.btAcessarTelaCliente();
    }//GEN-LAST:event_lb_clienteMouseClicked

    private void lb_instrutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_instrutorMouseClicked
        Main.controllerManager.btAcessarTelaInstrutor();        // TODO add your handling code here:
    }//GEN-LAST:event_lb_instrutorMouseClicked

    private void lb_planoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_planoMouseClicked
        Main.controllerManager.btAcessarTelaPlano();        // TODO add your handling code here:
    }//GEN-LAST:event_lb_planoMouseClicked

    private void lb_modalidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_modalidadeMouseClicked
        Main.controllerManager.btAcessarTelaModalidade();
    }//GEN-LAST:event_lb_modalidadeMouseClicked

    private void lb_treinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_treinoMouseClicked
        Main.controllerManager.btAcessarTelaTreino();
    }//GEN-LAST:event_lb_treinoMouseClicked

    private void lb_txtAddExercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_txtAddExercicioMouseClicked
        if(Main.controllerManager.getExercicioAdicionarController().verificaSetemMaisDe20(cb_Musculo.getSelectedItem().toString())){
            if(Main.controllerManager.getExercicioAdicionarController().validaCampo(tf_Nome.getText())){
                if(Main.controllerManager.getExercicioAdicionarController().verificaSeNomerepetido(tf_Nome.getText())){
                    exercicio.setNome(tf_Nome.getText());
                    exercicio.setMusculaturaAfetada(cb_Musculo.getSelectedItem().toString());
                    Main.controllerManager.getExercicioAdicionarController().bt_addExercicio(exercicio);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Exercicio ja cadastrado no sistema");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Preencha o campo nome");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Você ja cadastrou o máximo permitido de exercicios para sua assinatura. PAra cadastrar mais, remova alguns");
        }
    }//GEN-LAST:event_lb_txtAddExercicioMouseClicked

    private void lb_botaoAddExercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_botaoAddExercicioMouseClicked
        if(Main.controllerManager.getExercicioAdicionarController().verificaSetemMaisDe20(cb_Musculo.getSelectedItem().toString())){
            if(Main.controllerManager.getExercicioAdicionarController().validaCampo(tf_Nome.getText())){
                if(Main.controllerManager.getExercicioAdicionarController().verificaSeNomerepetido(tf_Nome.getText())){
                    exercicio.setNome(tf_Nome.getText());
                    exercicio.setMusculaturaAfetada(cb_Musculo.getSelectedItem().toString());
                    Main.controllerManager.getExercicioAdicionarController().bt_addExercicio(exercicio);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Exercicio ja cadastrado no sistema");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Preencha o campo nome");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Você ja cadastrou o máximo permitido de exercicios para sua assinatura. PAra cadastrar mais, remova alguns");
        }
    }//GEN-LAST:event_lb_botaoAddExercicioMouseClicked

    private void lb_exercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_exercicioMouseClicked
        Main.controllerManager.btAcessartelaExercicio();        // TODO add your handling code here:
    }//GEN-LAST:event_lb_exercicioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Musculo;
    private javax.swing.JLabel lb_Musculo;
    private javax.swing.JLabel lb_Nome;
    private javax.swing.JLabel lb_botaoAddExercicio;
    private javax.swing.JLabel lb_cliente;
    private javax.swing.JLabel lb_exercicio;
    private javax.swing.JLabel lb_instrutor;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_modalidade;
    private javax.swing.JLabel lb_plano;
    private javax.swing.JLabel lb_sideBar;
    private javax.swing.JLabel lb_titAddExec;
    private javax.swing.JLabel lb_treino;
    private javax.swing.JLabel lb_txtAddExercicio;
    private javax.swing.JTextField tf_Nome;
    // End of variables declaration//GEN-END:variables
}
